# Generated by Django 5.2.16 on 2026-07-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('hospital_admin', 'Hospital Admin'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('diagnostic_admin', 'Diagnostic Admin'), ('pharmacy_admin', 'Pharmacy Admin'), ('delivery_partner', 'Delivery Partner'), ('ambulance_driver', 'Ambulance Driver')], db_index=True, default='patient', max_length=30),
        ),
    ]
