version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pc_mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: purnia_care
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: pc_django_backend
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py seed_data &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-purnia-care-backend-development-secret-key-1994
      - DB_ENGINE=mysql
      - DB_NAME=purnia_care
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db

volumes:
  mysql_data:
