# Generated by Django 5.2.16 on 2026-07-20 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Basic Life Support (BLS)', 'Basic Life Support (BLS)'), ('Advanced Life Support (ALS)', 'Advanced Life Support (ALS)'), ('Neonatal/Pediatric Ambulance', 'Neonatal/Pediatric Ambulance')], default='Basic Life Support (BLS)', max_length=50)),
                ('driver_name', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Trip', 'On Trip')], default='Available', max_length=30)),
                ('charge_per_km', models.IntegerField(default=15)),
                ('eta_minutes', models.IntegerField(default=15)),
                ('location_name', models.CharField(default='Line Bazar', max_length=200)),
            ],
            options={
                'db_table': 'purnia_ambulances',
            },
        ),
        migrations.CreateModel(
            name='AmbulanceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_location', models.CharField(max_length=200)),
                ('destination_hospital', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Dispatched', 'Dispatched'), ('En Route', 'En Route'), ('Arrived', 'Arrived'), ('Completed', 'Completed')], default='Dispatched', max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='ambulance.ambulance')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purnia_ambulance_bookings',
            },
        ),
    ]
